title: BottledSheep Portfolio Log (and Weenieverse.....?)
logo: dachshund_1.jpg
description: Simple showcase of cyber threat mitigation projec-.........-Have you heard about the Weenieverse.....?

It’s this weird corner of the internet, all about dachshunds. But there’s a mystery!

A dachshund mystery?

The **Weenieverse** is waiting...
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
